development:
  adapter: postgresql
  encoding: unicode
  database: open_code_test_dev
  pool: 5
  username: open_code_test
  password: open_code_test

test:
  adapter: postgresql
  encoding: unicode
  database: open_code_test_test
  pool: 5
  username: open_code_test
  password: open_code_test

production:
  adapter: postgresql
  encoding: unicode
  database: open_code_test_prod
  pool: 5
  username: open_code_test
  password: open_code_test
